services:
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,HOST:PLAINTEXT'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,HOST://0.0.0.0:9094,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,HOST://localhost:9094'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CFG_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_LOG_RETENTION_MS: 300000
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - kafka-network
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server kafka:9092 || exit 1"]
      interval: 10s
      retries: 5
      start_period: 25s

  llm-service:
    build: .
    container_name: llm-service
    command: python llm_service.py
    ports:
      - "8000:8000"
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    networks:
      - kafka-network

  ambient-agent:
    build: .
    container_name: ambient-agent
    command: python consumer/pii_GPTmasker.py
    depends_on:
      kafka:
        condition: service_healthy
      llm-service:
        condition: service_started
    restart: unless-stopped
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
      - LLM_SERVICE_URL=http://llm-service:8000/mask
    # IMPORTANT: DO NOT MOUNT HOST CODE
    volumes:
      - ./data:/app/data
    networks:
      - kafka-network

  json-ingestor:
    build: .
    container_name: json-ingestor
    command: python ingestor/consumer_ingestor.py
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - KAFKA_BOOTSTRAP=kafka:9092
    volumes:
      - ./data:/app/data
    networks:
      - kafka-network

volumes:
  kafka_data:

networks:
  kafka-network:
    driver: bridge